name: Desplegar a Hostinger

on:
  push:
    branches: [ main ]

jobs:
  desplegar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, curl, zip, pdo_mysql

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Crear archivo .env temporal
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Instalar dependencias PHP
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev --optimize-autoloader"

      - name: Instalar dependencias Node
        run: npm ci

      - name: Compilar activos de React
        run: npm run build

      - name: Generar caché de la aplicación
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Preparar estructura de despliegue
        run: |
          # crear directorios
          mkdir -p deploy/laravel
          mkdir -p deploy/public_html

          # copiar archivos de aplicación (excluyendo el directorio public)
          rsync -av --exclude='public' --exclude='.git' --exclude='.github' --exclude='deploy' --exclude='node_modules' ./ deploy/laravel/

          # copiar archivos públicos a public_html
          rsync -av public/ deploy/public_html/

          # arreglar rutas de archivos en index.php para Laravel 12
          sed -i "s|require __DIR__.'/\.\./vendor/autoload.php';|require __DIR__.'/../laravel/vendor/autoload.php';|g" deploy/public_html/index.php
          sed -i "s|\$app = require_once __DIR__.'/\.\./bootstrap/app.php';|\$app = require_once __DIR__.'/../laravel/bootstrap/app.php';\n\$app->usePublicPath(__DIR__);|g" deploy/public_html/index.php

          # copiar .env a directorio laravel
          cp .env deploy/laravel/.env

      - name: Desplegar Laravel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/laravel/
          server-dir: /laravel/
          dangerous-clean-slate: false

      - name: Desplegar archivos públicos
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/public_html/
          server-dir: ./
          dangerous-clean-slate: false
